import type { RequestHandler } from "express";
import request from "supertest";
import { describe, expect, it } from "vitest";
import { createApp } from "../src/app.js";
import type { UserRole } from "../src/auth/authenticator.js";
import { loadBatchConfig } from "../src/delivery-batches/batch.config.js";
import type { BatchStore } from "../src/delivery-batches/batch.service.js";
const riderId="10000000-0000-0000-0000-000000000001", candidateOrderId="20000000-0000-0000-0000-000000000001", primaryOrderId="30000000-0000-0000-0000-000000000001", primaryAssignmentId="40000000-0000-0000-0000-000000000001", now=new Date("2026-08-31T12:00:00Z");
function authentication(users: Record<string,{userId:string;role:UserRole}>):RequestHandler{return(req,_res,next)=>{const key=req.header("authorization")?.replace(/^Bearer /,"");if(key&&users[key])req.auth=users[key];next()}}
const authenticate=authentication({admin:{userId:"00000000-0000-0000-0000-000000000001",role:"ADMIN"},rider:{userId:riderId,role:"DELIVERY_PARTNER"}})
interface Options{ineligibleRider?:boolean;stale?:boolean;existingBatch?:boolean;primaryStatus?:string;candidateStatus?:string;candidateAssigned?:boolean;far?:boolean;serializationFailures?:number}
function createStore(options:Options={}){const batches:any[]=[],offers:any[]=[],stops:any[]=[],updates:any[]=[];let attempts=0, assignmentLookups=0;const primary={id:primaryAssignmentId,status:options.primaryStatus??"ACCEPTED",order:{id:primaryOrderId,orderNumber:"MED-1",status:"RIDER_ASSIGNED",fulfillmentMethod:"DELIVERY",deliveryLatitudeSnapshot:28.65,deliveryLongitudeSnapshot:77.23,quotedEtaMinutes:20,pharmacy:{id:"p1",name:"Pharmacy A",latitude:28.61,longitude:77.21}}};const candidate={id:candidateOrderId,orderNumber:"MED-2",status:options.candidateStatus??"READY_FOR_PICKUP",fulfillmentMethod:"DELIVERY",deliveryLatitudeSnapshot:options.far?29.2:28.66,deliveryLongitudeSnapshot:options.far?78:77.24,quotedEtaMinutes:25,pharmacy:{id:"p2",name:"Pharmacy B",latitude:options.far?29:28.62,longitude:options.far?78:77.22}};const store:BatchStore={deliveryPartner:{findUnique:async()=>({id:riderId,isActive:!options.ineligibleRider,availability:"BUSY",currentLatitude:28.6,currentLongitude:77.2,lastLocationAt:new Date(now.getTime()-(options.stale?61000:5000)),user:{isActive:true}})},deliveryAssignment:{findFirst:async()=>{assignmentLookups++;return assignmentLookups===1?primary:(options.candidateAssigned?{id:"existing"}:null)},updateMany:async(args:any)=>{updates.push(args);return{count:1}},create:async(args:any)=>{const value={id:"50000000-0000-0000-0000-000000000001",...args.data};offers.push(value);return value}},order:{findUnique:async()=>candidate},deliveryBatch:{findFirst:async()=>options.existingBatch?{id:"batch",_count:{assignments:1}}:null,create:async(args:any)=>{const value={id:"60000000-0000-0000-0000-000000000001",riderId,status:args.data.status,createdAt:now};batches.push(value);return value}},deliveryStop:{createMany:async(args:any)=>{stops.push(...args.data);return{count:args.data.length}}},$transaction:async(callback)=>{attempts++;if(attempts<=(options.serializationFailures??0))throw Object.assign(new Error("conflict"),{code:"P2034"});return callback(store)}};return{store,batches,offers,stops,updates,get attempts(){return attempts}}}
function app(store:BatchStore,auth=authenticate){return createApp({store:store as any,authenticate:auth,now:()=>now,locationConfig:{sampleIntervalMs:15000,freshnessThresholdMs:60000},assignmentConfig:{offerTimeoutMs:30000},dispatchConfig:{maxCandidates:10,maxRadiusKm:15,workloadPenaltyKm:2},batchConfig:{maxAssignments:2,maxPharmacySeparationKm:3,maxDropoffSeparationKm:3,maxEstimatedDetourMinutes:15,assumedSpeedKmh:20}})}
describe("conservative rider batching",()=>{
 it("creates a two-order batch, offer, and valid pickup-before-drop-off stops",async()=>{const state=createStore();const response=await request(app(state.store)).post("/api/v1/delivery-batches/evaluate").set("Authorization","Bearer admin").send({riderId,candidateOrderId});expect(response.status).toBe(201);expect(state.batches).toHaveLength(1);expect(state.offers[0]).toMatchObject({riderId,batchId:state.batches[0].id,status:"OFFERED"});expect(state.updates[0].data).toEqual({batchId:state.batches[0].id});expect(state.stops.map(s=>s.stopType)).toEqual(["PHARMACY_PICKUP","PHARMACY_PICKUP","CUSTOMER_DROPOFF","CUSTOMER_DROPOFF"]);expect(state.stops.map(s=>s.sequence)).toEqual([1,2,3,4])});
 it("uses a valid three-stop sequence when the primary order is already picked up",async()=>{const state=createStore({primaryStatus:"PICKED_UP"});const response=await request(app(state.store)).post("/api/v1/delivery-batches/evaluate").set("Authorization","Bearer admin").send({riderId,candidateOrderId});expect(response.status).toBe(201);expect(state.stops.map(s=>s.stopType)).toEqual(["PHARMACY_PICKUP","CUSTOMER_DROPOFF","CUSTOMER_DROPOFF"])});
 it("rejects geographically incompatible orders without writes",async()=>{const state=createStore({far:true});const response=await request(app(state.store)).post("/api/v1/delivery-batches/evaluate").set("Authorization","Bearer admin").send({riderId,candidateOrderId});expect(response.status).toBe(409);expect(response.body.code).toBe("ORDERS_NOT_BATCH_COMPATIBLE");expect(state.batches).toEqual([])});
 it("rejects a candidate that already has a live assignment",async()=>{const state=createStore({candidateAssigned:true});const response=await request(app(state.store)).post("/api/v1/delivery-batches/evaluate").set("Authorization","Bearer admin").send({riderId,candidateOrderId});expect(response.status).toBe(409);expect(response.body.code).toBe("CANDIDATE_ALREADY_ASSIGNED");expect(state.batches).toEqual([])});
 it.each([[{ineligibleRider:true},"RIDER_NOT_BATCH_ELIGIBLE"],[{stale:true},"RIDER_LOCATION_STALE"],[{existingBatch:true},"BATCH_CAPACITY_REACHED"],[{candidateStatus:"PREPARING"},"CANDIDATE_ORDER_NOT_ELIGIBLE"]] as const)("rejects ineligible batching context",async(options,code)=>{const response=await request(app(createStore(options).store)).post("/api/v1/delivery-batches/evaluate").set("Authorization","Bearer admin").send({riderId,candidateOrderId});expect(response.status).toBe(409);expect(response.body.code).toBe(code)});
 it("requires admin and strict UUID input",async()=>{const forbidden=await request(app(createStore().store)).post("/api/v1/delivery-batches/evaluate").set("Authorization","Bearer rider").send({riderId,candidateOrderId});const invalid=await request(app(createStore().store)).post("/api/v1/delivery-batches/evaluate").set("Authorization","Bearer admin").send({riderId:"bad",candidateOrderId});expect(forbidden.status).toBe(403);expect(invalid.status).toBe(400)});
 it("retries serialization conflicts",async()=>{const state=createStore({serializationFailures:2});const response=await request(app(state.store)).post("/api/v1/delivery-batches/evaluate").set("Authorization","Bearer admin").send({riderId,candidateOrderId});expect(response.status).toBe(201);expect(state.attempts).toBe(3)});
 it("validates conservative configuration",()=>{expect(()=>loadBatchConfig({BATCH_MAX_ASSIGNMENTS:"3"})).toThrow();expect(()=>loadBatchConfig({BATCH_MAX_PHARMACY_SEPARATION_KM:"0"})).toThrow()});
 it("uses the default auth boundary",async()=>{const response=await request(createApp({store:createStore().store as any,locationConfig:{sampleIntervalMs:15000,freshnessThresholdMs:60000},assignmentConfig:{offerTimeoutMs:30000},dispatchConfig:{maxCandidates:10,maxRadiusKm:15,workloadPenaltyKm:2},batchConfig:{maxAssignments:2,maxPharmacySeparationKm:3,maxDropoffSeparationKm:3,maxEstimatedDetourMinutes:15,assumedSpeedKmh:20}})).post("/api/v1/delivery-batches/evaluate").send({riderId,candidateOrderId});expect(response.status).toBe(503)});
});
