import type { RequestHandler } from "express";
import request from "supertest";
import { describe, expect, it } from "vitest";
import { createApp } from "../src/app.js";
import type { UserRole } from "../src/auth/authenticator.js";
import type { DashboardStore } from "../src/rider-dashboard/dashboard.service.js";
const userId = "10000000-0000-0000-0000-000000000001", riderId = "20000000-0000-0000-0000-000000000001", now = new Date("2026-08-31T12:00:00Z");
function authentication(users: Record<string, { userId: string; role: UserRole }>): RequestHandler { return (req, _res, next) => { const token = req.header("authorization")?.replace(/^Bearer /, ""); if (token && users[token]) req.user = { id: users[token].userId, role: users[token].role }; next(); }; }
const authenticate = authentication({ rider: { userId, role: "DELIVERY_PARTNER" }, customer: { userId, role: "CUSTOMER" } });
function assignment(status: string, secondsAgo: number, batchId: string | null = null) { return { id: `${String(secondsAgo).padStart(8, "0")}-0000-0000-0000-000000000001`, batchId, status, assignedAt: new Date(now.getTime() - secondsAgo * 1000), acceptedAt: null, pickedUpAt: null, deliveredAt: status === "DELIVERED" ? now : null, order: { id: "order", orderNumber: `MED-${secondsAgo}`, status, deliveryAddressLabelSnapshot: "Home", deliveryAddressLine1Snapshot: "12 Main Road", deliveryLandmarkSnapshot: null, deliveryLatitudeSnapshot: 28.6, deliveryLongitudeSnapshot: 77.2, deliveryDistanceKm: 3, quotedEtaMinutes: 20, pharmacy: { id: "p", name: "Local Pharmacy", phone: "123", addressLine1: "Market Road", latitude: 28.61, longitude: 77.21 } } }; }
function store(overrides: { rider?: any; assignments?: any[]; batch?: any } = {}) { const queries: any[] = []; const value: DashboardStore = { deliveryPartner: { findUnique: async (args: any) => { queries.push(args); return overrides.rider === null ? null : overrides.rider ?? { id: riderId, userId, availability: "BUSY", vehicleType: "BIKE", vehicleNumber: "KA01", rating: "4.80", isActive: true, lastLocationAt: new Date(now.getTime() - 5000), user: { name: "Rahul S", phone: "999", isActive: true } }; } }, deliveryAssignment: { findMany: async () => overrides.assignments ?? [assignment("OFFERED", 10), assignment("ACCEPTED", 60), assignment("DELIVERED", 120)] }, deliveryBatch: { findFirst: async () => overrides.batch ?? null } }; return { value, queries }; }
function app(value: DashboardStore, auth = authenticate) { return createApp({ store: value as any, authenticate: auth, now: () => now, locationConfig: { sampleIntervalMs: 15000, freshnessThresholdMs: 60000 }, assignmentConfig: { offerTimeoutMs: 30000 }, dispatchConfig: { maxCandidates: 10, maxRadiusKm: 15, workloadPenaltyKm: 2 } }); }
describe("rider dashboard", () => {
  it("returns offers, active work, next action, freshness, counts and history", async () => { const state = store(); const response = await request(app(state.value)).get("/api/v1/riders/me/dashboard").set("Authorization", "Bearer rider"); expect(response.status).toBe(200); expect(response.body.data).toMatchObject({ rider: { id: riderId, availability: "BUSY" }, location: { freshness: "FRESH" }, workload: { actionableOffers: 1, activeAssignments: 1, recentDeliveries: 1 } }); expect(response.body.data.activeAssignments[0].nextAction).toBe("ARRIVE_PHARMACY_OR_PICKUP"); expect(state.queries[0].where).toEqual({ userId }); });
  it("omits expired offers", async () => { const response = await request(app(store({ assignments: [assignment("OFFERED", 30)] }).value)).get("/api/v1/riders/me/dashboard").set("Authorization", "Bearer rider"); expect(response.body.data.offers).toEqual([]); });
  it("classifies stale location", async () => { const custom = { id: riderId, availability: "AVAILABLE", vehicleType: "BIKE", vehicleNumber: null, rating: null, isActive: true, lastLocationAt: new Date(now.getTime() - 60001), user: { name: "R", phone: null, isActive: true } }; const response = await request(app(store({ rider: custom, assignments: [] }).value)).get("/api/v1/riders/me/dashboard").set("Authorization", "Bearer rider"); expect(response.body.data.location.freshness).toBe("STALE"); });
  it("includes the owning rider's optimized active stop sequence", async () => { const batchId = "30000000-0000-0000-0000-000000000001"; const batch = { id: batchId, status: "ACTIVE", stops: [{ id: "stop", assignmentId: "assignment", orderId: "order", stopType: "CUSTOMER_DROPOFF", sequence: 1, latitude: 28.6, longitude: 77.2, addressLabel: "Home", status: "PENDING", estimatedArrivalAt: now, assignment: { order: { orderNumber: "MED-1" } } }] }; const response = await request(app(store({ assignments: [assignment("ACCEPTED", 60, batchId)], batch }).value)).get("/api/v1/riders/me/dashboard").set("Authorization", "Bearer rider"); expect(response.status).toBe(200); expect(response.body.data.activeRoute).toMatchObject({ batchId, stops: [{ orderNumber: "MED-1", sequence: 1 }] }); });
  it("requires rider role and hides missing profiles", async () => { const forbidden = await request(app(store().value)).get("/api/v1/riders/me/dashboard").set("Authorization", "Bearer customer"); const missing = await request(app(store({ rider: null }).value)).get("/api/v1/riders/me/dashboard").set("Authorization", "Bearer rider"); expect(forbidden.status).toBe(403); expect(missing.status).toBe(404); });
  it("uses the Platform Core authentication boundary by default", async () => { const response = await request(createApp({ store: store().value as any, locationConfig: { sampleIntervalMs: 15000, freshnessThresholdMs: 60000 }, assignmentConfig: { offerTimeoutMs: 30000 }, dispatchConfig: { maxCandidates: 10, maxRadiusKm: 15, workloadPenaltyKm: 2 } })).get("/api/v1/riders/me/dashboard"); expect(response.status).toBe(401); expect(response.body.code).toBe("AUTH_REQUIRED"); });
});
