import "dotenv/config";
import { createApp } from "./app.js";
import { prisma } from "./db/prisma.js";
import type { RiderStore } from "./riders/rider.service.js";
import type { LocationStore } from "./location/location.service.js";
import type { DeliveryQuoteStore } from "./delivery-quotes/delivery-quote.service.js";
import type { AssignmentStore } from "./delivery-assignments/assignment.service.js";
import type { DispatchStore } from "./dispatch/dispatch.service.js";
import type { LifecycleStore } from "./delivery-lifecycle/lifecycle.service.js";
import type { TrackingStore } from "./customer-tracking/tracking.service.js";
import type { DashboardStore } from "./rider-dashboard/dashboard.service.js";
import type { BatchStore } from "./delivery-batches/batch.service.js";
import type { RouteStore } from "./delivery-routing/route.service.js";
const port = Number(process.env.PORT ?? 3000);
createApp({ store: prisma as unknown as RiderStore & LocationStore & DeliveryQuoteStore & AssignmentStore & DispatchStore & LifecycleStore & TrackingStore & DashboardStore & BatchStore & RouteStore }).listen(port, () => console.log(`MediConnect backend listening on port ${port}`));
